var names = ["alert",
    "anquanjiance",
    "anquanweixie",
    "bangzhu",
    "beifen",
    "bianji",
    "bianji1",
    "block",
    "books",
    "bumenbushu",
    "celue",
    "celueguanli",
    "chenggong",
    "chongqi",
    "chongqi2",
    "chongsao",
    "chufa",
    "close",
    "cunhuotance",
    "cunhuotance1",
    "daochu exl",
    "daochu pdf",
    "daochu ppt",
    "daochu word",
    "daochu xml",
    "daochu",
    "dbupload",
    "dengdai",
    "display",
    "downarray",
    "exl",
    "fabushijian",
    "fanhui",
    "fengxian",
    "fengxianguanli",
    "fengxianliebiao",
    "fuwuqi",
    "fuzeren",
    "gaowei,zhongwei,diwei",
    "gongfang logo",
    "gonggao1",
    "guanbi",
    "guanji",
    "heikedangan",
    "huifu",
    "jiancha",
    "jianqie",
    "jiantou shang",
    "jiantou xia",
    "jiantou you",
    "jiantou zuo",
    "jichushuju",
    "jiesuo",
    "jifen",
    "jingji",
    "jingji1",
    "jinsai",
    "jinxing",
    "jinxingzhong",
    "jinzhi",
    "kaiji",
    "kaishi",
    "kechengnandu",
    "kuaizhao",
    "kuaizhaohuigun",
    "kulou",
    "leftarray",
    "lixian",
    "loudong",
    "loudongxiufu",
    "manleft",
    "md",
    "meirizixun",
    "moban",
    "pass",
    "pdf",
    "ppt",
    "qingli",
    "qizhi",
    "qushi-jiang",
    "qushi-sheng",
    "quyu",
    "remenshijian",
    "ren",
    "renwuchuangjian",
    "renwuguanli",
    "renwuliebiao",
    "rili",
    "riqi",
    "rizhishenji",
    "saiti",
    "saomiao",
    "saomiaochenggong",
    "saomiaochucuo",
    "shanchu",
    "shangchuan",
    "shenji",
    "shenpi",
    "shezhi",
    "shibai",
    "shijianfenxi",
    "shiping",
    "shishijiankong",
    "shouji",
    "shouye",
    "shuaxin",
    "shudigongan",
    "sousuo",
    "suo",
    "tendency",
    "tianjia",
    "tingzhi",
    "tishi,jingshi",
    "tishi",
    "tongbaoyujing",
    "tongji",
    "tongzhi",
    "tuandui",
    "tuichu",
    "tuopu",
    "uparray",
    "upload",
    "wenjianjia",
    "word",
    "xiafa",
    "xiangqing",
    "xiazai",
    "xinxi",
    "xitongshengji",
    "xiugai",
    "xiugai1",
    "xml",
    "xukeguanli",
    "xunhuan",
    "xuniji",
    "yingjichuzhi",
    "yinqingshezhi",
    "yonghu",
    "yonghushezhi",
    "youjian",
    "youjianshezhi",
    "yulan",
    "yunxingzhong",
    "zanting",
    "zhiding",
    "zhongdianwangzhan",
    "zhongdianwangzhanbaowei",
    "zhuanjiazhishou",
    "ziaxian",
    "zichanchuangjian",
    "zichanguanli",
    "zichanliebiao",
    "zuidaihua",
    "zuixiaohua.svg"];

function getDom(name) {
    return '<li><i class="fonticon ah-' + name + '" style="font-size: 3em;"></i><span class="icon-name"><span>' + name + '</span></span><div class="icon-cover"><span class="cover-item cover-item-line fonticon ah-' + name + '"></span><span class="cover-item cover-item-line" style="font-size: small">' + name + '</span> <span class="cover-item cover-item-line" style="font-size: small" onclick="copy_this(this)">复制</span></div></li>'
}
var string = '';
for (var i = 0; i < names.length; i++) {
    string += getDom(names[i]);
}
console.info(string);